version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    versioning-strategy: "auto"
    open-pull-requests-limit: 10
    allow:
      - dependency-type: "all"
    ignore:
      - dependency-type: "all"
        update-types: ["version-update:semver-major"]
